"""agregado columna patron_movimiento a ejercicio

Revision ID: 04cd6f7ebe8f
Revises: f68b7ca8fea6
Create Date: 2026-09-09 14:00:43.312146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cd6f7ebe8f'
down_revision = 'f68b7ca8fea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patron_movimiento', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_ejercicio_patron_movimiento'), ['patron_movimiento'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejercicio_patron_movimiento'))
        batch_op.drop_column('patron_movimiento')

    # ### end Alembic commands ###
