"""agregada tabla de recomendaciones

Revision ID: 1655c9aa6d0c
Revises: ea9f4e5fcd78
Create Date: 2026-09-23 20:01:02.719627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1655c9aa6d0c'
down_revision = 'ea9f4e5fcd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recomendacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recomendacion_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_entrenador_id'), ['entrenador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_fecha'), ['fecha'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recomendacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recomendacion_fecha'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_entrenador_id'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_cliente_id'))

    op.drop_table('recomendacion')
    # ### end Alembic commands ###
