"""Agregado tablas de usuarios, entrenadores y clientes

Revision ID: 6b446cf0da33
Revises: 
Create Date: 2026-09-01 09:09:04.610649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b446cf0da33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=64), nullable=False),
    sa.Column('contraseña', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_nombre_usuario'), ['nombre_usuario'], unique=True)

    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('meta', sa.String(length=12), nullable=False),
    sa.Column('nivel_experiencia', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrenador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_entrenador', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrenador')
    op.drop_table('cliente')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_nombre_usuario'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
