"""Agregado la relacion Cliente-Entrenador y minor fixes en como se refencian las FK)

Revision ID: 7fc2d9853938
Revises: 6b446cf0da33
Create Date: 2026-09-01 11:04:13.812357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc2d9853938'
down_revision = '6b446cf0da33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrenador_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_cliente_entrenador_id'), ['entrenador_id'], unique=False)
        batch_op.create_foreign_key('fk_cliente_entrenador', 'entrenador', ['entrenador_id'], ['id'])

    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrenador_codigo_entrenador'), ['codigo_entrenador'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrenador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrenador_codigo_entrenador'))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cliente_entrenador', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cliente_entrenador_id'))
        batch_op.drop_column('entrenador_id')

    # ### end Alembic commands ###
