"""creadas tablas de rutina sesion y prescripcion

Revision ID: c9f0493d469e
Revises: 04cd6f7ebe8f
Create Date: 2026-09-11 10:00:51.071162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f0493d469e'
down_revision = '04cd6f7ebe8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nivel', sa.String(length=12), nullable=False),
    sa.Column('meta', sa.String(length=12), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rutina', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rutina_entrenador_id'), ['entrenador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rutina_nombre'), ['nombre'], unique=False)

    op.create_table('sesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutina_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sesion_rutina_id'), ['rutina_id'], unique=False)

    op.create_table('prescripcion_ejercicio_sesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('series', sa.Integer(), nullable=False),
    sa.Column('repeticiones', sa.String(length=20), nullable=False),
    sa.Column('descanso_segundos', sa.Integer(), nullable=True),
    sa.Column('intensidad', sa.String(length=30), nullable=True),
    sa.Column('notas', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prescripcion_ejercicio_sesion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescripcion_ejercicio_sesion_ejercicio_id'), ['ejercicio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescripcion_ejercicio_sesion_sesion_id'), ['sesion_id'], unique=False)

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rutina_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cliente_rutina_id'), ['rutina_id'], unique=False)
        batch_op.create_foreign_key('fk_cliente_rutina', 'rutina', ['rutina_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cliente_rutina', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cliente_rutina_id'))
        batch_op.drop_column('rutina_id')

    with op.batch_alter_table('prescripcion_ejercicio_sesion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescripcion_ejercicio_sesion_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_prescripcion_ejercicio_sesion_ejercicio_id'))

    op.drop_table('prescripcion_ejercicio_sesion')
    with op.batch_alter_table('sesion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sesion_rutina_id'))

    op.drop_table('sesion')
    with op.batch_alter_table('rutina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rutina_nombre'))
        batch_op.drop_index(batch_op.f('ix_rutina_entrenador_id'))

    op.drop_table('rutina')
    # ### end Alembic commands ###
