"""agregado_peso_objetivo_y_dias_semana_meta_a_cliente

Revision ID: cfc5b5ed3e23
Revises: ea9f4e5fcd78
Create Date: 2026-09-23 20:41:13.304733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc5b5ed3e23'
down_revision = 'ea9f4e5fcd78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_objetivo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dias_semana_meta', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('dias_semana_meta')
        batch_op.drop_column('peso_objetivo')

    # ### end Alembic commands ###
