"""creadas tablas de registro de sesiones series y peso

Revision ID: ea9f4e5fcd78
Revises: c9f0493d469e
Create Date: 2026-09-19 12:42:14.091757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9f4e5fcd78'
down_revision = 'c9f0493d469e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registro_peso_corporal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_peso_corporal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_peso_corporal_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_peso_corporal_fecha'), ['fecha'], unique=False)

    op.create_table('registro_sesion_entrenamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('sesion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('estado_animo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_sesion_entrenamiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_sesion_entrenamiento_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_sesion_entrenamiento_sesion_id'), ['sesion_id'], unique=False)

    op.create_table('registro_ejercicio_sesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_sesion_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('notas_adicionales', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicio.id'], ),
    sa.ForeignKeyConstraint(['registro_sesion_id'], ['registro_sesion_entrenamiento.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_ejercicio_sesion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_ejercicio_sesion_ejercicio_id'), ['ejercicio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registro_ejercicio_sesion_registro_sesion_id'), ['registro_sesion_id'], unique=False)

    op.create_table('registro_serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=False),
    sa.Column('peso_usado', sa.Float(), nullable=False),
    sa.Column('repeticiones_logradas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['registro_ejercicio_id'], ['registro_ejercicio_sesion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_serie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_serie_registro_ejercicio_id'), ['registro_ejercicio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_serie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_serie_registro_ejercicio_id'))

    op.drop_table('registro_serie')
    with op.batch_alter_table('registro_ejercicio_sesion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_ejercicio_sesion_registro_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_registro_ejercicio_sesion_ejercicio_id'))

    op.drop_table('registro_ejercicio_sesion')
    with op.batch_alter_table('registro_sesion_entrenamiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_sesion_entrenamiento_sesion_id'))
        batch_op.drop_index(batch_op.f('ix_registro_sesion_entrenamiento_cliente_id'))

    op.drop_table('registro_sesion_entrenamiento')
    with op.batch_alter_table('registro_peso_corporal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_peso_corporal_fecha'))
        batch_op.drop_index(batch_op.f('ix_registro_peso_corporal_cliente_id'))

    op.drop_table('registro_peso_corporal')
    # ### end Alembic commands ###
