"""agregada tabla de ejercicios

Revision ID: f68b7ca8fea6
Revises: 7fc2d9853938
Create Date: 2026-09-09 12:45:26.627800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f68b7ca8fea6'
down_revision = '7fc2d9853938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('grupo_muscular', sa.String(length=50), nullable=False),
    sa.Column('entrenador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrenador_id'], ['entrenador.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ejercicio_entrenador_id'), ['entrenador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejercicio_grupo_muscular'), ['grupo_muscular'], unique=False)
        batch_op.create_index(batch_op.f('ix_ejercicio_nombre'), ['nombre'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ejercicio_nombre'))
        batch_op.drop_index(batch_op.f('ix_ejercicio_grupo_muscular'))
        batch_op.drop_index(batch_op.f('ix_ejercicio_entrenador_id'))

    op.drop_table('ejercicio')
    # ### end Alembic commands ###
